name: Octicons
on: push
jobs:
  prepare:
    name: Prepare, test, and lint icons
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: |
        npm install
        npm run lint
    - uses: ./.github/actions/version
    - uses: primer/figma-action@d7844a
      env:
        FIGMA_FILE_URL: https://www.figma.com/file/FP7lqd1V00LUaT5zvdklkkZr/Octicons
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      with:
        args: format=svg dir=./lib/build
    - run: npm test
    - uses: actions/upload-artifact@master
      with:
        name: icon-library
        path: ./lib/build
    - run: ls -lha ./lib/build
