name: Octicons
on: push
jobs:
  # Prepare
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm install
    - uses: ./.github/actions/version
    - uses: primer/figma-action@d7844a
      env:
        FIGMA_FILE_URL: https://www.figma.com/file/FP7lqd1V00LUaT5zvdklkkZr/Octicons
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      with:
        args: format=svg dir=./lib/build
