name: Octicons
on: push
jobs:
  lint:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm run lint
  icons:
    name: Fetch, generate, and test icons
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm install
    # - uses: ./.github/actions/version
    - uses: primer/figma-action@d7844a
      env:
        FIGMA_FILE_URL: https://www.figma.com/file/FP7lqd1V00LUaT5zvdklkkZr/Octicons
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      with:
        args: format=svg dir=./lib/build
    - run: npm test
    - uses: actions/upload-artifact@master
      with:
        name: icons
        path: ./lib/build
